name = "living-poster"
main = "src/index.ts"
compatibility_date = "2022-09-19"

[triggers]
crons = ["55 * * * *"]

[[kv_namespaces]]
binding = "LIVING_POSTER"
id = "67f8656ce21147b292f046e373caffc4"
preview_id = "49a0e7f7324c4760a6cdb401f9d63e77"
